title: Developing with Accessibility
description: Resources for Building Baseline Usability Across Platforms
author: Jamal Mazrui
theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 2..3